name: "Code Quality Checks"

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ruff-code-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Ruff code check
        uses: astral-sh/ruff-action@v4.1.0
        with:
          version-file: uv.lock

      - name: Ruff format check
        run: ruff format --check
